name: grpc

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/grpc.yml'
      - 'ports/grpc/**'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/grpc.yml'
      - 'ports/grpc/**'

jobs:

  build:
    runs-on: self-hosted
    if: |
      (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
      (github.event_name == 'pull_request' && contains(github.event.pull_request.title, 'grpc'))
    steps:
    - name: Checkout build-files
      uses: actions/checkout@v4
      with:
        path: build-files

    - name: Checkout muslflt
      uses: actions/checkout@v4
      with:
        repository: qnx-ports/muslflt
        path: muslflt

    - name: Checkout googletest
      uses: actions/checkout@v4
      with:
        repository: qnx-ports/googletest
        path: googletest

    - name: Checkout abseil-cpp
      uses: actions/checkout@v4
      with:
        repository: qnx-ports/abseil-cpp
        path: abseil-cpp

    - name: Checkout benchmark
      uses: actions/checkout@v4
      with:
        repository: qnx-ports/benchmark
        path: benchmark

    - name: Checkout protobuf
      uses: actions/checkout@v4
      with:
        repository: qnx-ports/protobuf
        path: protobuf

    - name: Download SDP 8.0
      env:
        LICENSE_KEY: ${{ secrets.LICENSE_KEY }}
        MYQNX_USER: ${{ secrets.MYQNX_USER }}
        MYQNX_PASSWORD: ${{ secrets.MYQNX_PASSWORD }}
      run: |
        echo "Downloading QNX Software Center ..."
        mkdir ${{ github.workspace }}/.qnx
        curl -v --cookie-jar ${{ github.workspace }}/.qnx/myqnxcookies.auth --form "userlogin=$MYQNX_USER" --form "password=$MYQNX_PASSWORD" -X POST https://www.qnx.com/account/login.html > login_response.html
        curl -v -L --cookie ${{ github.workspace }}/.qnx/myqnxcookies.auth https://www.qnx.com/download/download/77351/qnx-setup-2.0.3-202408131717-linux.run > qnx-setup-lin.run
        chmod a+x qnx-setup-lin.run
        ./qnx-setup-lin.run force-override disable-auto-start agree-to-license-terms ${{ github.workspace }}/qnxinstall
        echo "Installing License ..."
        ${{ github.workspace }}/qnxinstall/qnxsoftwarecenter/qnxsoftwarecenter_clt -syncLicenseKeys -myqnx.user="$MYQNX_USER" -myqnx.password="$MYQNX_PASSWORD" -addLicenseKey $LICENSE_KEY
        cp -r ~/.qnx/license ${{ github.workspace }}/.qnx
        echo "Downloading QNX SDP ..."
        ${{ github.workspace }}/qnxinstall/qnxsoftwarecenter/qnxsoftwarecenter_clt -mirror -cleanInstall -destination ${{ github.workspace }}/qnx800 -installBaseline com.qnx.qnx800 -myqnx.user="$MYQNX_USER" -myqnx.password="$MYQNX_PASSWORD"

    - name: Build the Docker image
      run: |
        cd build-files/docker && ./docker-build-qnx-image.sh

    - name: Build grpc
      uses: addnab/docker-run-action@v3
      with:
        image: qnx800:latest
        options: -v ${{ github.workspace }}:/home/runner
        shell: bash
        run: |
          source ~/qnx800/qnxsdp-env.sh
          QNX_PROJECT_ROOT="$(pwd)/muslflt" make -C build-files/ports/muslflt/ install JLEVEL=16
          BUILD_TESTING="OFF" QNX_PROJECT_ROOT="$(pwd)/googletest" make -C build-files/ports/googletest/ install JLEVEL=16
          QNX_SEVEN_COMPAT="true" QNX_PROJECT_ROOT="$(pwd)/abseil-cpp" make -C build-files/ports/abseil-cpp/ install JLEVEL=16
          QNX_PROJECT_ROOT="$(pwd)/benchmark" make -C build-files/ports/benchmark JLEVEL=16 install
          cd protobuf
          git submodule update --init
          cd -
          QNX_PROJECT_ROOT="$(pwd)/protobuf" make -C build-files/ports/protobuf install JLEVEL=16
          cd grpc
          git submodule update --init
          cd third_party/googletest
          git remote add qnx https://github.com/qnx-ports/googletest.git
          git fetch --all
          git switch qnx_v1.13.0 
          git pull
          cd ../../../
          QNX_PROJECT_ROOT="$(pwd)/grpc" HOST_PROTOC_PATH="$(pwd)/build-files/ports/protobuf/host_protoc" make -C build-files/ports/grpc/ install JLEVEL=16
